### ISSUE TITLE
The end of SGX

### ISSUE THREAD

**Issue by LifeIsStrange** [Liaojinghui/awesome-sgx#4]
https://cdn.wccftech.com/wp-content/uploads/2020/03/Intel-Rocket-Lake-S-VideoCardz.jpg
The next generation of Intel cpus will drop SGX support. I don't *think* there is a successor.

**Comment by Jim8y** [comment]
TEE is critical to chip vendors, I don't think they just directly remove SGX, must have something else to replace SGX.

**Comment by LifeIsStrange** [comment]
Yeah someone said to me they are preparing SGX2 so SGX will continue to be supported for future intel cpus, but maybe that rocket lake will not support it and support will not comeback until tiger lake (end of 2021).
